apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: 445567117729.dkr.ecr.eu-west-1.amazonaws.com/project-a/sample-repo:latest
        ports:
        - containerPort: 443